### ISSUE TITLE
Sign Up page Design is flawed

### ISSUE THREAD

**Issue by abhinav2712** [Avinash905/HealthBooker#1]
Once we go to signup page, this is how it looks:
![image](https://user-images.githubusercontent.com/68495520/224625641-bedfe373-6c20-47a8-97ab-64883ab4074c.png)

I can fix this, and also improve the UI, assign this issue to me and I can work on it
Thanks

**Comment by abhinav2712** [comment]
@Avinash905  May i know the setup steps after npm install? On npm start, nothing is happening

**Comment by Avinash905** [comment]
You need to run the backend and frontend on separate terminals. npm start
in the main directory will only run the backend. To run frontend change the
directory to the client folder and then do npm start.
