### ISSUE TITLE
What are .env credintals and how to add them?

### ISSUE THREAD

**Issue by creativetechify** [Avinash905/HealthBooker#3]
REACT_APP_SERVER_DOMAIN=http://127.0.0.1:5000/api
REACT_APP_CLOUDINARY_BASE_URL=https://api.cloudinary.com/v1_1/{CLOUD_NAME}/image/upload
REACT_APP_CLOUDINARY_CLOUD_NAME=YOUR_OWN_CLOUDINARY_CLOUD_NAME
REACT_APP_CLOUDINARY_PRESET=YOUR_OWN_CLOUDINARY_PRESET
?? from where i will get these credentials, i am very new to ![Screenshot (7)](https://github.com/Avinash905/HealthBooker/assets/77048516/017c8729-ec1b-4c3d-a6c0-89b918558e43), please help, without this my register page is throwing error: POST https://api.cloudinary.com/v1_1/dc325ixbs/image/upload 400 (Bad Request)

**Comment by Avinash905** [comment]
**.env** files are secret files that are only visible to you and not exposed to everyone when you upload to github.

Just you need to add a file with the extension **.env** in your frontend and your backend with the mentioned variables. You need to create a cloudinary account and add cloudinary related variables in the frontend file.

**Comment by creativetechify** [comment]
thnx, now please tell how to deply it, please mention all steps as i am beginner

**Comment by Avinash905** [comment]
1. Upload the project to github 
2. Create an account on render
3. Go to render.com dashboard
4. Click on **New** then click on **Web Service**
5. Connect with the github repository where you have uploaded the project
6. Give some name for your website, change the build command to **npm install** and change the start command to **npm start**
7. Scroll down and click on **Advanced** and click on **Add Environment Variable** and add all the content in only the backend's .env file.
8. Click on **Create Web Service** and wait for some time for your application to deploy
9. After your application is deployed you can open the link that is provided to you

**Comment by creativetechify** [comment]
Its giving me error while registering or login with database accounts, my github repo: https://github.com/creativetechify/HealthBooker, i have ran: npm run build in my client, then uploaded my repo to render, and my env (client) are: REACT_APP_SERVER_DOMAIN="http://127.0.0.1:5000/api"
REACT_APP_CLOUDINARY_BASE_URL="https://api.cloudinary.com/v1_1/dc325ixbs/image/upload"
REACT_APP_CLOUDINARY_CLOUD_NAME="dc325ixbs"
REACT_APP_CLOUDINARY_PRESET="eajj71it" and my deplyed link: https://doctorapp-i4sl.onrender.com
![Screenshot (8)](https://github.com/Avinash905/HealthBooker/assets/77048516/ee93ff7b-ab89-4afe-b355-70c0405b8ecd)
![Screenshot (9)](https://github.com/Avinash905/HealthBooker/assets/77048516/2ff874f9-a544-4cc0-a67b-e71fad5a29ea)

**Comment by Avinash905** [comment]
REACT_APP_SERVER_DOMAIN="http://127.0.0.1:5000/api" is only for running locally

If you are deploying your application then change **REACT_APP_SERVER_DOMAIN** in client's .env to your deployed link and add **/api** at the end. 
Example:  REACT_APP_SERVER_DOMAIN=https://doctorapp-i4sl.onrender.com/api

**Comment by Avinash905** [comment]
> If you are deploying your application then change **REACT_APP_SERVER_DOMAIN** in client's .env to your deployed link and add **/api** at the end. 
Example: REACT_APP_SERVER_DOMAIN=https://doctorapp-i4sl.onrender.com/api

**Comment by creativetechify** [comment]
thnx thnx a lot but one last thing please help 
one want to make appointment page looks responisve in table like admin one, please help
appointment page (user) is not that much good, please help
![Screenshot (10)](https://github.com/Avinash905/HealthBooker/assets/77048516/db223ea0-89d4-4c02-b48d-6d40c99a18a9)
![Screenshot (11)](https://github.com/Avinash905/HealthBooker/assets/77048516/10e33489-4346-4b69-a369-a9e08a62b1bc)

**Comment by creativetechify** [comment]
Please improve User Appointment's Page
![Screenshot (12)](https://github.com/Avinash905/HealthBooker/assets/77048516/21af0933-5386-4599-8aa7-ceabfa4e6a54)
