### ISSUE TITLE
User's appointments page improvement, please

### ISSUE THREAD

**Issue by creativetechify** [Avinash905/HealthBooker#6]
I want to make appointment page looks responsive like admin one
![Screenshot (10)](https://github.com/Avinash905/HealthBooker/assets/77048516/03c66971-767b-4860-aa92-71b378b4abdf)
![Screenshot (11)](https://github.com/Avinash905/HealthBooker/assets/77048516/f2bdb06e-4255-472e-83ac-8e285c304c87)
 like admin one, please help
appointment page (user) is not that much good, please help

**Comment by Avinash905** [comment]
You can change your css as you want

**Comment by creativetechify** [comment]
sir, please help this time, what css styling i need to do,  pleas help
